name: Deploy website
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: cached-deps-${{hashFiles('**/package-lock.json')}}
      - name: Install dependencies
        run: npm ci
      - name: Lint code
        run: npm run lint
      - name: Test code
        run: npm run test
  build:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      script-name: ${{steps.publish-js-name.outputs.built-file-name}}
      name: ${{steps.publish-js-name.outputs.name}}
      age: ${{steps.publish-js-name.outputs.age}}
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: cached-deps-${{hashFiles('**/package-lock.json')}}
      - name: Install dependencies
        run: npm ci
      - name: Build website
        run: npm run build
      - name: Publish JS name
        id: publish-js-name
        run: |
          find dist/assets/*.js -type f -execdir echo 'built-file-name={}' >> $GITHUB_OUTPUT ';'
          echo "name=Olzhas" >> $GITHUB_OUTPUT
          echo "age=33" >> $GITHUB_OUTPUT
      - name: Upload artifact
        uses: actions/upload-artifact@v6
        with:
          name: Dist Files
          path: dist
        # with:
        #   name: Dist Files
        #   path: |
        #     dist
        #     package.json
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get built artifacts
        uses: actions/download-artifact@v6
        with:
          name: Dist Files
      - name: Output contents
        run: ls
      - name: Publish Info from BUILD Step
        run: |
          echo "my name is ${{needs.build.outputs.name}}"
          echo "my age is ${{needs.build.outputs.age}}"
      - name: Deploy
        run: echo "Deploying..."
